// 01.simple_website/angular/src/app/components/jumbotron/jumbotron.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-jumbotron',
  templateUrl: './jumbotron.component.html',
  styleUrls: ['./jumbotron.component.scss']
})
export class JumbotronComponent implements OnInit {
  public jbtHeading: string = 'Hello world!';
  public jbtText: string = 'Angular Material buttons are native <button> or <a> elements enhanced with Material Design styling and ink ripples.';
  public jbtButton: string = 'Read More';
  constructor() { }

  ngOnInit() {
  }

}

<div class="jumbotron">
  <div class="container">
    <h1>{{ jbtHeading }}</h1>
    <p>{{ jbtText }}</p>
    <button mat-raised-button color="primary">{{ jbtButton }}</button>
  </div>
</div>

// 01.simple_website/react_website/src/components/Jumbotron/index.tsx
import './Jumbotron.css';

import Button from '@material-ui/core/Button';
import React from 'react';


const jbtHeading: string = 'Hello world!';
const jbtText: string = 'Buttons allow users to take actions, and make choices, with a single tap.';
const jbtButton: string = 'Read More';

const Jumbotron = () => {
	return (
		<div className="jumbotron">
			<div className="container">
				<h1>{jbtHeading}</h1>
				<p>{jbtText}</p>
				<Button variant="contained" color="primary" >
					{jbtButton}
				</Button>
			</div>
		</div>
	);
}

export default Jumbotron;
